server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/bddknowix
    username: postgres
    password: abc123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  #Keycloak Config
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Knowix
          jwk-set-uri: http://localhost:8080/realms/Knowix/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: knowix_frontend

logging:
  level:
    org:
      keycloak: DEBUG

# Configuración para la API de Exercisedb
exercisedb:
  api-key: a64c039307msh0dfa7564941492dp1a0237jsn0fe875c24192
