### Crear un cupón:
POST http://localhost:8081/api/cupones/crear
Content-Type: application/json

{
  "discountType": "Percentage",
  "discountAmount": 15.00,
  "cuponCode": "DISCOUNT2024",
  "startDate": "2024-06-01T00:00:00",
  "endDate": "2024-06-30T23:59:59",
  "minAmountPurchase": 50.00,
  "descriptionPromotion": "Descuento del 15% en todas las compras de junio"
}

### Listar todos los cupones:
GET http://localhost:8081/api/cupones/listar

### Buscar cupón por ID:
GET http://localhost:8081/api/cupones/buscar/14

