### Obtener todos los idiomas:
GET http://localhost:8081/api/v1/language

### Obtener idioma por id:
GET http://localhost:8081/api/v1/language/3


### agregar:
POST http://localhost:8081/api/v1/language
Content-Type: application/json

{
    "languageName": "arabzzzzeee",
    "status": true
}
