POST http://localhost:8081/api/v1/paymentmethod
Content-Type: application/json

{
  "ciPerson": "12345678",
  "nameOwner": "Juan Perez",
  "phoneNumber": "123456789",
  "qrImage": "/////path",
  "accountNumber": "125670ll",
  "bankBankId": 1,
  "kcUserKcUuid": "05f0b4fa-e28b-409f-96ec-1f3d2f505554",
  "accountTypeAccountTypeId": 1
}

### obtener pagos de un usuario por uuid:

GET http://localhost:8081/api/v1/paymentmethod/user/05f0b4fa-e28b-409f-96ec-1f3d2f505554



### obtener metodo de pago por id:
GET http://localhost:8081/api/v1/paymentmethod/1


### prueba:

GET http://localhost:8081/api/v1/paymentmethod/user/05f0b4fa-e28b-409f-96ec-1f3d2f505554