apiVersion: v1
kind: Service
metadata:
  name: knowix-backend
spec:
  selector:
    app: knowix-backend
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowix-backend
spec:
  selector:
    matchLabels:
      app: knowix-backend
  template:
    metadata:
      labels:
        app: knowix-backend
    spec:
      containers:
      - name: knowix-backend
        image: us-central1-docker.pkg.dev/knowix-421914/knowix-repo/knowix_backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8081
