apiVersion: v1
kind: Service
metadata:
  name: knowix-db
spec:
  selector:
    app: knowix-db
  ports:
  - port: 5434
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowix-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowix-db
  template:
    metadata:
      labels:
        app: knowix-db
    spec:
      containers:
      - name: knowix-db
        image: us-central1-docker.pkg.dev/knowix-421914/knowix-repo/knowix_db
        env: 
          - name: POSTGRES_PASSWORD
            value: "abc123"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5434
